### ISSUE TITLE
PHPStorm Codestyle: Leerzeile um PHPDoc Tags auf FALSE

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/Codex#54]
Es geht um folgende Option in den PHPStorm Codestyles:

```
<option name="PHPDOC_BLANK_LINES_AROUND_PARAMETERS" value="true" />
```

Der aktuelle Wert (`true`) erzeugt solche DocBlogs:

```
/**
 * Method summary in one sentence.
 *
 * @wp-hook manage_posts_columns
 *
 * @param  Array $columns List of columns
 *
 * @return Array List of columns
 */
```

Ich finde die Leerzeilen unnötig. Wenn wir den Wert auf `false` setzen sähe das Ergebnis so aus:

```
/**
 * Method summary in one sentence.
 *
 * @wp-hook manage_posts_columns
 * @param Array $columns array List of columns
 * @return Array List of columns
 */
```

Das nimmt nicht ganz so viel Platz ein und ist immer noch lesbar.

Spricht etwas dagegen?

**Comment by dasllama** [comment]
Llama mag das.

**Comment by danielhuesken** [comment]
Ich mag es eigentlich wenn zwischen dem Returns und den Params eine Leerzeile ist.

**Comment by Biont** [comment]
Der Fairness halber noch ein Beispiel, in dem etwas mehr los ist>


```
/**
 *
 * Return the price depending on user role and quantity
 *
 * @wp-hook woocommerce_get_price
 * @wp-hook woocommerce_get_sale_price
 * @wp-hook woocommerce_get_regular_price
 *
 * @param $price
 * @param $product
 *
 * @return mixed
 */
```

Ich finde, die Absätze dienen hier schon der Übersicht.

**Comment by tfrommen** [comment]
Ganz klar pro Leerzeile!

**Comment by bueltge** [comment]
Dafür.

**Comment by tfrommen** [comment]
Wen es interessiert, der kann ja auch mal einen Blick in den sich in der Entwicklung befindlichen [PSR-5-Standard](https://github.com/phpDocumentor/fig-standards/blob/8abaef4e48364c5b0f99207cdff1068bdb16f03a/proposed/phpdoc.md) oder den [WordPress Style Guide](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/), der sich am PSR-5 orientiert, werfen.

**Comment by Chrico** [comment]
Generell würde ich da auch weg von eigener Suppe und hin zu Standardisierungen (WP, PSR) wenn es Code Style und Formatting geht. 

Sehe unseren Codex auch nicht mehr ganz so als "CodeStyle"-Vorgabe, sondern als BestPractice (Theme Architektur) und Vorlagen (z.B. Pluginvorlage - welche nicht aktuell/zeitgemäß ist). Natürlich müsste hier noch einiges an Arbeit investiert werden (Testung, verschiedene Anwenderszenarien, ...).

**Comment by bueltge** [comment]
Ich finde nicht, dass man alles adaptieren muss, die Frage von David ist einfach und ich sehe da benefit im Bezug Lesbarkeit, machen wir es nicht, tut es auch nie weh. Aber die paar Anpassungen im XML tun nicht weh.

**Comment by dnaber-de** [comment]
> Und zur Sache noch mal: Wenn es ein paar Leute gibt, die es mit Leerzeilen lesbarer finden, und einige, > die darin keine erhöhte Lesbarkeit sehen, dann sollten wir dennoch Leerzeilen verwenden. Denn 
> unlesbarer wird der Header dadurch ja wohl nicht.
>
> >  Das nimmt nicht ganz so viel Platz ein...
> 
> Platz ist aber keine Mangelware oder?

Wenn _ich_ den Code quer lese, dann überspringe ich die DocBlocks und beginne mit der Signatur der Methode/Funktion. Pi mal Daumen 90% der Methoden haben einen DocBlock der nicht viel größer ist als mein Beispiel. Ich wollte sehen, ob das die Mehrheit auch so sieht. Wenn das einige als schwerer lesbar empfinden, belassen wir, wie es ist.

**Comment by dnaber-de** [comment]
> Generell würde ich da auch weg von eigener Suppe…
Hier stimme ich dir zu, aber manche Dinge in PSR, wie z.B. das Einrücken mit Leerzeichen, sind nur schwer verdaulich.
