### ISSUE TITLE
Branch »draft« entfernen

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/Codex#60]
Im Rahmen des großen Aufräumens hier schlage ich vor, den Branch »draft« zu beerdigen. Der ist ohnehin uralt. 

Gegenstimmen? 

Wir sollten uns entscheiden, ob wir die drafts tatsächlich auf Verzeichnisebene pflegen wollen, oder wir nur noch das accepted-Verzeichnis pflegen und Änderungen prinzipiell über Issues und dazugehörige Branches vorschlagen und dann über Pull-Requests oder einfache Merges _akzeptieren_.

**Comment by bueltge** [comment]
+1 für NUR Issues und Branches, keine Ordner , Branch Draft

**Comment by tfrommen** [comment]
Branch `draft` entfernt.
