### ISSUE TITLE
JSHint

### ISSUE THREAD

**Issue by tfrommen** [inpsyde/Codex#62]
# JSHint

>JSHint is a program that flags suspicious usage in programs written in JavaScript. The core project consists of a library itself as well as a CLI program distributed as a Node module.
>
>[Docs](http://jshint.com/docs/) · [List of all JSHint options](http://jshint.com/docs/options/) · [Command-line Interface](http://jshint.com/docs/cli/) · [API](http://jshint.com/docs/api/) · [Writing your own reporter](http://jshint.com/docs/reporters/) · [FAQ](http://jshint.com/docs/faq/)

## Verwendung

JSHint kann via [npm](https://www.npmjs.com/) sowohl mit [Grunt](http://gruntjs.com/) (siehe [grunt-contrib-jshint](https://github.com/gruntjs/grunt-contrib-jshint)), als auch mit [Travis CI](https://travis-ci.org/) genutzt werden. Darüber hinaus ist [JSHint auch in PhpStorm integriert](https://www.jetbrains.com/phpstorm/help/jshint.html).

### Grunt

Beispielhafte Verwendung von JSHint mit Grunt:

```js
/* globals module, require */
module.exports = function( grunt ) {
	'use strict';

	var _ = require( 'lodash' );

	var configObject = {
		config: {
			scripts_src  : 'resources/js/'
		},

		// https://github.com/gruntjs/grunt-contrib-jshint
		jshint: {
			options: {
				jshintrc: true
			},
			grunt  : {
				src: [ 'Gruntfile.js' ]
			},
			scripts: {
				expand: true,
				cwd   : '<%= config.scripts_src %>',
				src   : [ '**/*.js' ]
			}
		},

		// https://github.com/gruntjs/grunt-contrib-watch
		watch: {
			options: {
				dot     : true,
				spawn   : true,
				interval: 2000
			},
			grunt  : {
				files: 'Gruntfile.js',
				tasks: [ 'jshint:grunt' ]
			},
			scripts: {
				files: '<%= config.scripts_src %>**/*.js',
				tasks: [ 'jshint:scripts' ]
			}
		}
	};

	// Add development target for JSHint
	configObject.jshint.dev = _.merge(
		{},
		configObject.jshint.scripts,
		{
			options: {
				devel: true,
				force: true
			}
		}
	);

	grunt.initConfig( configObject );

	// https://github.com/sindresorhus/load-grunt-tasks
	require( 'load-grunt-tasks' )( grunt );

	grunt.registerTask( 'grunt', [ 'jshint:grunt' ] );
	grunt.registerTask( 'scripts', [ 'jshint:scripts' ] );
	grunt.registerTask( 'devScripts', [ 'jshint:dev' ] );

	grunt.registerTask( 'default', [ 'devScripts' ] );
	grunt.registerTask( 'production', [ 'scripts' ] );
	grunt.registerTask( 'test', [ 'jshint' ] );
};
```

### Travis CI

Beispielhafte Verwendung von JSHint mit Travis CI:

```yaml
language: php

php:
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_script:
  - npm install -g jshint

script:
  - jshint src
```

## Einstellungen

JSHint verarbeitet (in der Regel) zwei optionale Dateien: `.jshintignore` und `.jshintrc`.

### `.jshintignore`

Die Datei `.jshintignore` beinhaltet, analog zu `.gitignore`, Dateien/Pfade, die JSHint ingorieren soll.

Hier sind beispielsweise minifizierte Dateien oder externe Bibliotheken einzutragen.

```
src/**/*.min.js
vendor/some/lib/*.js
```

### `.jshintrc`

Die Datei `.jshintrc` beinhaltet die Konfiguration der möglichen [Optionen von JSHint](http://jshint.com/docs/options/).

[WordPress](https://develop.svn.wordpress.org/trunk/.jshintrc) verwendet beispielsweise die folgende Konfiguration:

```json
{
	"boss": true,
	"curly": true,
	"eqeqeq": true,
	"eqnull": true,
	"es3": true,
	"expr": true,
	"immed": true,
	"noarg": true,
	"onevar": true,
	"quotmark": "single",
	"trailing": true,
	"undef": true,
	"unused": true,

	"browser": true,

	"globals": {
		"_": false,
		"Backbone": false,
		"jQuery": false,
		"JSON": false,
		"wp": false
	}
}
```

## Und nun?

Es wäre wohl sinnvoll, wenn diejenigen, die JSHint verwenden wollen, **gemeinsam** eine Konfiguration erarbeiten/wählen.

---

Das Issue dient zunächst als Diskussionsgrundlage. Später wird es dann als Teil des (neuen) Codex umgeschrieben. So zumindest der Plan.

**Comment by Chrico** [comment]
+1 Für die WordPress-`..jshintrc`.

Sollen wird die dann in jeden Plugin mitliefern, oder global jeder bei sich bzw. auf den (noch nicht vorhanden )Test-Servern (z.B. Travis CI) ablegen?

**Comment by tfrommen** [comment]
Das hängt davon ab, wie/wo man das nutzen will.
Grunt und Travis CI (siehe Beispiele) holen sie sich via npm. Wenn du das Tool von Hand ansoßen willst, brauchst du die Config lokal (wie auch immer du drankommen magst). PhpStorm selbst hat JSHint integriert, muss aber unserer Konfig entsprechend eingerichtet werden.
Das wäre aber der nächste Schritt.

**Comment by dnaber-de** [comment]
Ich wäre dafür, solche Dinge mit im VCS ablegt. Dann hat man Codebasis und _aktuelle_ Qualitätskriterien beisammen. Im Gegensatz dazu würde eine globale Datei dazu führen, dass alle bisherigen Projekte in den Tests durchfallen, wenn man sich mal zu einer Änderung entschließt.

**Comment by Chrico** [comment]
Ich denke, dass das nichts macht wenn Projekte durchfallen. Eine Änderung am Codex von Inpsyde muss ja nicht immer heißen, dass alle Projekte valide bleiben. Manchmal sind da Brüche notwendig und wenn es möglich ist, ziehen wir die alten Projekte natürlich nach.

**Comment by obstschale** [comment]
Erstmal +1 für JSHint. Das verbessert sicherlich unseren JS code. Ich denke, dass es auf jeden fall sinnvoll und nötig ist, die `.jshintrc` und vielleicht sogar eine allgemeine `.jshintignore` hier im Codex abzulegen. Dann hat man immer einen Ort wo man die aktuellste Version finden kann. Wenn ein Projekt neu startet kann man dann hier die neuste Version sich ziehen.

Ich finde aber auch, dass wenn sich die Config ändern eine Globale config stören würde, gerade wenn man in alten Projekte noch mal was fixen muss und plötzlich bekommt man 1000 Fehler Meldungen.

Für den Start würde ich empfehlen JSHint mit PhpStorm zu nutzen, da nicht jedes Projekt schon mit Grunt aufgesetzt ist und auch in meine Augen nicht nötig ist. Aber auf jeden Fall wäre ich auch dafür JSHint mit TravisCI oder mit unserem Jenkins zu nutzen.

**Comment by tfrommen** [comment]
Für unser Meeting nachher:

## Optionen, die wir *verwenden* sollten:

```json
	// Enforcing
	"curly": true,
	"eqeqeq": true,
	"esversion": 3,
	"noarg": true,
	"undef": true,
	"unused": true,

	// Environments
	"browser": true,
	"jQuery": false,
```

## Optionen, die wir *nicht* verwenden sollten:

```json
	// Enforcing
	"es3" // deprecated (-> "esversion": 3)
	"immed" // deprecated
	"onevar" // gibt es nicht
	"quotmark" // deprecated
	"trailing" // gibt es nicht
```

## Optionen, die wir *diskutieren* sollten:

```json
	// Enforcing
	"forin": true,
	"freeze": true,
	"futurehostile": true,
	"globals": {
		"_": false,
		"Backbone": false,
		"JSON": false,
		"wp": false
	},
	"latedef": true,
	"nonbsp": true,
	"nonew": true,
	"singleGroups": true,
	"strict": true,

	// Relaxing
	"boss": true,
	"eqnull": true,
	"expr": true,

	// Environments
	"qunit": false,
```

**Comment by dnaber-de** [comment]
Auf welche Version von JSHInt beziehst Du dich? Ich habe noch Storm 9 und da ist Version 2.8.0 die neueste. Einige Optionen (z.B. `esversion` sehe ich dort nicht). (Spielt aber auch keine große Rolle, wir wollen ja ohnehin eine Config-Datei verwenden.

**Comment by tfrommen** [comment]
@dnaber-de ich bin nach der [offiziellen Dokumentation](http://jshint.com/docs/options/#es3) gegangen. Wie es scheint, wurden die [`es*`s mit Version 2.9.0 deprecated](https://github.com/jshint/jshint/blob/2.9.0/src/options.js#L89-L106).

**Comment by dnaber-de** [comment]
Ich habe Thorstens Vorschläge mal in einem kleinen Gist zusammengefast: https://gist.github.com/dnaber-de/2000a3473d8c05c6589c

Ihr könnt euch das clonen und in PHPStorm öffen. In der Readme steht, wie ihr JSHint aktiviert. 

Soll als Diskusionsgrundlage dienen.

**Comment by tfrommen** [comment]
Im heutigen Meeting haben wir [JSHint-Dateien](https://github.com/inpsyde/Codex/tree/master/tools/JSHint) erarbeitet.

**Comment by tfrommen** [comment]
Für JSHint ist soweit alles klar. Mittlerweile sollten wir aber ESLint verwenden (s. [hier](https://github.com/inpsyde/javascript)).
